version: "3.9"
services:
  frontend:
    working_dir: /app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    command: npm run dev
    ports:
      - 5000:5000
    networks:
      - shoes

networks:
  shoes:
    name: shoes